# Generated by Django 5.2.1 on 2025-06-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_reset', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MonthlyPrice',
        ),
    ]
