# Generated by Django 5.2.1 on 2025-07-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_module', '0002_totalsales_delete_monthlyprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TotalSales',
        ),
    ]
