# Generated by Django 5.2.1 on 2025-06-04 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors_numbers', models.CharField(choices=[('', '-- تعداد نویسندگان --'), ('1', 'یک'), ('2', 'دو'), ('3', 'سه'), ('4', 'چهار')], max_length=20, verbose_name='تعداد نویسندگان')),
                ('main_goal', models.CharField(max_length=200, verbose_name='محور اصلی مقاله')),
                ('language', models.CharField(choices=[('persian', 'فارسی'), ('english', 'انگلیسی')], max_length=100, verbose_name='زبان مقاله')),
                ('persian_subject', models.TextField(verbose_name='عنوان فارسی مقاله')),
                ('english_subject', models.TextField(verbose_name='عنوان انگلیسی مقاله')),
                ('english_Abstract', models.TextField(max_length=250, verbose_name='چکیده انگلیسی')),
                ('persian_Abstract', models.TextField(max_length=250, verbose_name='چکیده فارسی')),
                ('main_persian_words', models.TextField(verbose_name='کلمات کلیدی فارسی')),
                ('main_english_words', models.TextField(verbose_name='کلمات کلیدی انگلیسی')),
                ('sources', models.TextField(verbose_name='منابع')),
                ('file', models.FileField(upload_to='articles/', verbose_name='فایل مقاله')),
                ('submit_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت مقاله')),
                ('is_visited', models.BooleanField(default=False, verbose_name='دیده شده توسط ادمین')),
                ('is_coached', models.BooleanField(default=False, verbose_name='داوری شده')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='پذیرفته شده توسط داور')),
                ('is_paid', models.BooleanField(default=False, verbose_name='هزینه داوری')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='ArticleAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='نام نویسنده')),
                ('last_name', models.CharField(max_length=200, verbose_name='نام خانوادگی نویسنده')),
                ('english_first_name', models.CharField(max_length=200, verbose_name='نام انگلیسی نویسنده')),
                ('english_last_name', models.CharField(max_length=200, verbose_name='نام خانوادگی انگلیسی نویسنده')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل نویسنده')),
                ('main_author', models.BooleanField(default=False, verbose_name='نویسنده مسئول')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_module.article', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
            },
        ),
        migrations.CreateModel(
            name='ArticleCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_url', models.CharField(default='', max_length=300, verbose_name='آدرس تقدیر نامه')),
                ('image', models.ImageField(upload_to='certificates/', verbose_name='عکس تقدیر نامه')),
                ('cer_id', models.CharField(max_length=16, unique=True, verbose_name='شماره گواهی ')),
                ('certificate_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اعطا')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='article_module.article', verbose_name='مقاله')),
                ('authors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='article_module.articleauthor', verbose_name='نویسندگان')),
            ],
            options={
                'verbose_name': 'گواهی مقاله',
                'verbose_name_plural': 'گواهی های مقالات',
            },
        ),
    ]
