# Generated by Django 5.2.1 on 2025-05-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Field_of_Study',
            new_name='field_of_study',
        ),
        migrations.AlterField(
            model_name='user',
            name='postal_code',
            field=models.CharField(max_length=10, verbose_name='کد پستی'),
        ),
    ]
