# Generated by Django 5.2.1 on 2025-05-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_rename_field_of_study_user_field_of_study_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
    ]
