# Generated by Django 5.2.1 on 2025-05-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_alter_user_address_alter_user_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='degree',
            field=models.CharField(choices=[('', ' -- مدرک تحصیلی خود را انتخاب کنید --'), ('دیپلم', 'دیپلم'), ('کارشناسی', 'کارشناسی'), ('کارشناسی ارشد', 'کارشناسی ارشد'), ('دکتری', 'دکتری')], max_length=200, verbose_name='مدرک تحصیلی'),
        ),
    ]
