# Generated by Django 5.2.1 on 2025-05-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0005_alter_user_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='degree',
            field=models.CharField(choices=[('', ' -- مدرک تحصیلی  --'), ('دیپلم', 'دیپلم'), ('کارشناسی', 'کارشناسی'), ('کارشناسی ارشد', 'کارشناسی ارشد'), ('دکتری', 'دکتری')], max_length=200, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kind_of_signup',
            field=models.CharField(choices=[('', '--نوع ثبت نام--'), ('دانشجویی', 'دانشجویی'), ('استاد دانشگاه', 'استاد دانشگاه')], max_length=300, verbose_name='نوع ثبت نام'),
        ),
    ]
